Terminating namespace
redhat-chaos/cerberus pull request #156
Opened 2021-08-19 17:29 UTC by paigerube14

### Description
Adding watch of terminating namespaces.  This will asses if any of the namespaces in the list of watch_namespaces are terminating and alert/set the no-go signal 

### Fixes
https://github.com/cloud-bulldozer/cerberus/issues/155

2022-07-11 17:56 UTC, janosdebugs requested changes

2022-07-11 17:56 UTC, janosdebugs commented on cerberus/kubernetes/client.py
> +            logging.error("Exception when calling CoreV1Api->list_namespaced_pod: %s\n" % e)
The process here continues after logging the error with the assumption that `ret` is set. The entire block should be wrapped in the `try-except`or the error should be handled.

2022-08-08 14:20 UTC, chaitanyaenr commented on cerberus/kubernetes/client.py
> +            logging.error("Exception when calling CoreV1Api->list_namespaced_pod: %s\n" % e)
Maybe sys.exit(1) to handle this case? Thoughts?

Also s/list_namespaced_pod/list_namespace.

2022-08-08 18:25 UTC, chaitanyaenr approved these changes
LGTM

2022-08-09 11:03 UTC, merged